NAME = philo
CC = cc
CFLAGS = -Wall -Wextra -Werror -I.
SRCS = main.c parse.c init.c launch.c routine.c actions.c monitor.c \
	time.c log.c cleanup.c
OBJS = $(SRCS:.c=.o)

all: $(NAME)

$(NAME): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(NAME)

%.o: %.c philo.h
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
